### ISSUE TITLE
Integrate `centraldashboard` rock

### ISSUE THREAD

**Issue by orfeas-k** [canonical/kubeflow-rocks#100] opened 2024-06-10 10:41 UTC
### Context

Integrate above rock to corresponding charm

### What needs to get done

Integrate rock to charm

### Definition of Done

Rock is integrated and charm is tested and works

**Comment by DnPlas** [comment] 2024-07-25 07:48
Closing as a duplicate of https://github.com/canonical/kubeflow-rocks/issues/113

**Closed by DnPlas** 2024-07-25 07:48 UTC
Labels: enhancement, Kubeflow 1.9
